# Generated by Django 4.1.2 on 2023-04-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Filiallar', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangiliklar', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='newsdetail',
            options={'verbose_name': 'Yangilik 2-qism', 'verbose_name_plural': 'Yangilik 2-qism'},
        ),
        migrations.AlterModelOptions(
            name='spirituality',
            options={'verbose_name': 'Maʼnaviyat va maʼrifat', 'verbose_name_plural': 'Maʼnaviyat va maʼrifat'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='director',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='director',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='director',
            name='title_ky',
            field=models.CharField(max_length=250, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='director',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='director',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch', verbose_name='Filiallar'),
        ),
        migrations.AlterField(
            model_name='management',
            name='name',
            field=models.CharField(max_length=212, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='name_en',
            field=models.CharField(max_length=212, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='name_ky',
            field=models.CharField(max_length=212, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='name_ru',
            field=models.CharField(max_length=212, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='name_uz',
            field=models.CharField(max_length=212, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='title_ky',
            field=models.CharField(max_length=250, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='management',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Yangilik content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Yangilik content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Yangilik content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Yangilik content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Yangilik content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.CharField(blank=True, max_length=333, null=True, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=333, null=True, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=333, null=True, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=333, null=True, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=333, null=True, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=222, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=222, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=222, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=222, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=222, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='content',
            field=models.TextField(null=True, verbose_name='Yangilik contenti 2'),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Yangilik contenti 2'),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Yangilik contenti 2'),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Yangilik contenti 2'),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Yangilik contenti 2'),
        ),
        migrations.AlterField(
            model_name='spirituality',
            name='image',
            field=models.ImageField(upload_to='Spirituality/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='spirituality',
            name='title',
            field=models.CharField(max_length=333, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='spirituality',
            name='title_en',
            field=models.CharField(max_length=333, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='spirituality',
            name='title_ky',
            field=models.CharField(max_length=333, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='spirituality',
            name='title_ru',
            field=models.CharField(max_length=333, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='spirituality',
            name='title_uz',
            field=models.CharField(max_length=333, null=True, verbose_name='Sarlavha'),
        ),
    ]
