# Generated by Django 4.2.1 on 2023-05-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_branch_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='documents')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='director',
            name='address',
            field=models.CharField(max_length=223, verbose_name='Qabul kunlari'),
        ),
        migrations.AlterField(
            model_name='director',
            name='address_en',
            field=models.CharField(max_length=223, null=True, verbose_name='Qabul kunlari'),
        ),
        migrations.AlterField(
            model_name='director',
            name='address_ky',
            field=models.CharField(max_length=223, null=True, verbose_name='Qabul kunlari'),
        ),
        migrations.AlterField(
            model_name='director',
            name='address_ru',
            field=models.CharField(max_length=223, null=True, verbose_name='Qabul kunlari'),
        ),
        migrations.AlterField(
            model_name='director',
            name='address_uz',
            field=models.CharField(max_length=223, null=True, verbose_name='Qabul kunlari'),
        ),
    ]
