# Generated by Django 4.2.1 on 2023-05-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_document_alter_director_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
        migrations.AddField(
            model_name='document',
            name='day',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='month',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='month_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='month_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='month_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='month_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
