# Generated by Django 4.2.1 on 2023-05-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_news_content_alter_news_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterTarkibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=212, verbose_name='Name')),
                ('name_en', models.CharField(max_length=212, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=212, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=212, null=True, verbose_name='Name')),
                ('name_ky', models.CharField(max_length=212, null=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('title', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('title_ky', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('phone', models.CharField(max_length=70, verbose_name='Phone')),
                ('address', models.CharField(max_length=223, verbose_name='Qabul kunlari')),
                ('address_en', models.CharField(max_length=223, null=True, verbose_name='Qabul kunlari')),
                ('address_uz', models.CharField(max_length=223, null=True, verbose_name='Qabul kunlari')),
                ('address_ru', models.CharField(max_length=223, null=True, verbose_name='Qabul kunlari')),
                ('address_ky', models.CharField(max_length=223, null=True, verbose_name='Qabul kunlari')),
            ],
            options={
                'verbose_name': 'Markaz Tarkibi',
                'verbose_name_plural': 'Markaz Tarkibi',
            },
        ),
    ]
