# Generated by Django 4.2.1 on 2023-05-31 12:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_en', models.TextField(null=True)),
                ('question_uz', models.TextField(null=True)),
                ('question_ru', models.TextField(null=True)),
                ('question_ky', models.TextField(null=True)),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_uz', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
                ('answer_ky', models.TextField(null=True)),
            ],
            options={
                'verbose_name': "Ko'pincha so'raladigan savollar",
                'verbose_name_plural': "Ko'pincha so'raladigan savollar",
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=223)),
                ('name_en', models.CharField(max_length=223, null=True)),
                ('name_uz', models.CharField(max_length=223, null=True)),
                ('name_ru', models.CharField(max_length=223, null=True)),
                ('name_ky', models.CharField(max_length=223, null=True)),
            ],
            options={
                'verbose_name': 'Funksiya va Vazifalari',
                'verbose_name_plural': 'Funksiya va vazifalar',
            },
        ),
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('text_ky', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=450)),
                ('title_en', models.CharField(max_length=450, null=True)),
                ('title_uz', models.CharField(max_length=450, null=True)),
                ('title_ru', models.CharField(max_length=450, null=True)),
                ('title_ky', models.CharField(max_length=450, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_ky', ckeditor.fields.RichTextField(null=True)),
                ('sub_image', models.ImageField(upload_to='images/')),
                ('sub_title', models.CharField(max_length=450)),
                ('sub_title_en', models.CharField(max_length=450, null=True)),
                ('sub_title_uz', models.CharField(max_length=450, null=True)),
                ('sub_title_ru', models.CharField(max_length=450, null=True)),
                ('sub_title_ky', models.CharField(max_length=450, null=True)),
                ('sub_content', ckeditor.fields.RichTextField()),
                ('sub_content_en', ckeditor.fields.RichTextField(null=True)),
                ('sub_content_uz', ckeditor.fields.RichTextField(null=True)),
                ('sub_content_ru', ckeditor.fields.RichTextField(null=True)),
                ('sub_content_ky', ckeditor.fields.RichTextField(null=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_func', to='functions.functions')),
            ],
        ),
    ]
